# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogtoolbox.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialogtoolbox(object):
    def setupUi(self, dialogtoolbox):
        dialogtoolbox.setObjectName("dialogtoolbox")
        dialogtoolbox.resize(435, 208)
        font = QtGui.QFont()
        font.setFamily("Arial")
        dialogtoolbox.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(dialogtoolbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(dialogtoolbox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setAutoFillBackground(False)
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.edtTags = QtWidgets.QLineEdit(self.tab)
        self.edtTags.setObjectName("edtTags")
        self.gridLayout.addWidget(self.edtTags, 5, 1, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.edtRemark = QtWidgets.QLineEdit(self.tab)
        self.edtRemark.setObjectName("edtRemark")
        self.gridLayout.addWidget(self.edtRemark, 2, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.edtSex = QtWidgets.QLineEdit(self.tab)
        self.edtSex.setObjectName("edtSex")
        self.gridLayout.addWidget(self.edtSex, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 2, 1, 1)
        self.edtName = QtWidgets.QLineEdit(self.tab)
        self.edtName.setObjectName("edtName")
        self.gridLayout.addWidget(self.edtName, 4, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.edtCity = QtWidgets.QLineEdit(self.tab)
        self.edtCity.setObjectName("edtCity")
        self.gridLayout.addWidget(self.edtCity, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.edtProv = QtWidgets.QLineEdit(self.tab)
        self.edtProv.setObjectName("edtProv")
        self.gridLayout.addWidget(self.edtProv, 1, 1, 1, 1)
        self.edtType = QtWidgets.QLineEdit(self.tab)
        self.edtType.setObjectName("edtType")
        self.gridLayout.addWidget(self.edtType, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnSearch = QtWidgets.QPushButton(self.tab)
        self.btnSearch.setObjectName("btnSearch")
        self.horizontalLayout_2.addWidget(self.btnSearch)
        self.btnInvalid = QtWidgets.QPushButton(self.tab)
        self.btnInvalid.setObjectName("btnInvalid")
        self.horizontalLayout_2.addWidget(self.btnInvalid)
        self.btnNoremark = QtWidgets.QPushButton(self.tab)
        self.btnNoremark.setObjectName("btnNoremark")
        self.horizontalLayout_2.addWidget(self.btnNoremark)
        self.btnNotags = QtWidgets.QPushButton(self.tab)
        self.btnNotags.setObjectName("btnNotags")
        self.horizontalLayout_2.addWidget(self.btnNotags)
        self.gridLayout.addLayout(self.horizontalLayout_2, 7, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(dialogtoolbox)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dialogtoolbox)
        dialogtoolbox.setTabOrder(self.edtProv, self.edtCity)
        dialogtoolbox.setTabOrder(self.edtCity, self.edtSex)
        dialogtoolbox.setTabOrder(self.edtSex, self.edtRemark)
        dialogtoolbox.setTabOrder(self.edtRemark, self.edtType)
        dialogtoolbox.setTabOrder(self.edtType, self.edtName)
        dialogtoolbox.setTabOrder(self.edtName, self.edtTags)

    def retranslateUi(self, dialogtoolbox):
        _translate = QtCore.QCoreApplication.translate
        dialogtoolbox.setWindowTitle(_translate("dialogtoolbox", "客户信息管理"))
        self.label_5.setText(_translate("dialogtoolbox", "省份："))
        self.label_7.setText(_translate("dialogtoolbox", "标签："))
        self.label_4.setText(_translate("dialogtoolbox", "城市："))
        self.label_8.setText(_translate("dialogtoolbox", "备注："))
        self.label_6.setText(_translate("dialogtoolbox", "性别："))
        self.label_2.setText(_translate("dialogtoolbox", "类型："))
        self.label_9.setText(_translate("dialogtoolbox", "名字："))
        self.btnSearch.setText(_translate("dialogtoolbox", "根据条件过滤"))
        self.btnInvalid.setText(_translate("dialogtoolbox", "所有失效"))
        self.btnNoremark.setText(_translate("dialogtoolbox", "所有易混淆"))
        self.btnNotags.setText(_translate("dialogtoolbox", "所有无标签"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("dialogtoolbox", "通讯录管理"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialogtoolbox = QtWidgets.QDialog()
    ui = Ui_dialogtoolbox()
    ui.setupUi(dialogtoolbox)
    dialogtoolbox.show()
    sys.exit(app.exec_())

