# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlggroupmgr.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlggroupmgr(object):
    def setupUi(self, dlggroupmgr):
        dlggroupmgr.setObjectName("dlggroupmgr")
        dlggroupmgr.resize(640, 480)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(dlggroupmgr)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblGroupName = QtWidgets.QLabel(dlggroupmgr)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lblGroupName.setFont(font)
        self.lblGroupName.setObjectName("lblGroupName")
        self.gridLayout.addWidget(self.lblGroupName, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(dlggroupmgr)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.lblTotalCnt = QtWidgets.QLabel(dlggroupmgr)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lblTotalCnt.setFont(font)
        self.lblTotalCnt.setObjectName("lblTotalCnt")
        self.gridLayout.addWidget(self.lblTotalCnt, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(dlggroupmgr)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lblFriendCnt = QtWidgets.QLabel(dlggroupmgr)
        self.lblFriendCnt.setObjectName("lblFriendCnt")
        self.horizontalLayout_2.addWidget(self.lblFriendCnt)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.twFriends = QtWidgets.QTableView(dlggroupmgr)
        self.twFriends.setObjectName("twFriends")
        self.verticalLayout_3.addWidget(self.twFriends)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.edtTag = QtWidgets.QLineEdit(dlggroupmgr)
        self.edtTag.setObjectName("edtTag")
        self.horizontalLayout_4.addWidget(self.edtTag)
        self.btnTags = QtWidgets.QPushButton(dlggroupmgr)
        self.btnTags.setObjectName("btnTags")
        self.horizontalLayout_4.addWidget(self.btnTags)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(dlggroupmgr)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.lblUnknowCnt = QtWidgets.QLabel(dlggroupmgr)
        self.lblUnknowCnt.setObjectName("lblUnknowCnt")
        self.horizontalLayout_3.addWidget(self.lblUnknowCnt)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.twUnknown = QtWidgets.QTableView(dlggroupmgr)
        self.twUnknown.setObjectName("twUnknown")
        self.verticalLayout_4.addWidget(self.twUnknown)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.edtHello = QtWidgets.QLineEdit(dlggroupmgr)
        self.edtHello.setObjectName("edtHello")
        self.horizontalLayout_5.addWidget(self.edtHello)
        self.btnAddFriends = QtWidgets.QPushButton(dlggroupmgr)
        self.btnAddFriends.setObjectName("btnAddFriends")
        self.horizontalLayout_5.addWidget(self.btnAddFriends)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(dlggroupmgr)
        QtCore.QMetaObject.connectSlotsByName(dlggroupmgr)

    def retranslateUi(self, dlggroupmgr):
        _translate = QtCore.QCoreApplication.translate
        dlggroupmgr.setWindowTitle(_translate("dlggroupmgr", "群聊详情"))
        self.lblGroupName.setText(_translate("dlggroupmgr", "中国摄影行业协会重庆市巴南区分会"))
        self.label_4.setText(_translate("dlggroupmgr", "成员数："))
        self.lblTotalCnt.setText(_translate("dlggroupmgr", "TextLabel"))
        self.label_5.setText(_translate("dlggroupmgr", "我的好友："))
        self.lblFriendCnt.setText(_translate("dlggroupmgr", "TextLabel"))
        self.btnTags.setText(_translate("dlggroupmgr", "批量标签"))
        self.label_8.setText(_translate("dlggroupmgr", "未加好友："))
        self.lblUnknowCnt.setText(_translate("dlggroupmgr", "TextLabel"))
        self.edtHello.setText(_translate("dlggroupmgr", "您好，我从群聊中加的您"))
        self.btnAddFriends.setText(_translate("dlggroupmgr", "批量加好友"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlggroupmgr = QtWidgets.QDialog()
    ui = Ui_dlggroupmgr()
    ui.setupUi(dlggroupmgr)
    dlggroupmgr.show()
    sys.exit(app.exec_())

